### ISSUE TITLE
Filter 'autoClose' option does not work

### ISSUE THREAD

**Issue by EligiusSantori** [milesj/decoda#100]
code: `Lorem ipsum[br]dolor [b]sit[/b] amet`
what i expected: `Lorem ipsum<br/>dolor <strong>sit</strong> amet`
what i got: `Lorem ipsumdolor sit amet`

Thanks.

**Comment by milesj** [comment]
You need to close with a slash `[br/]`.

**Comment by EligiusSantori** [comment]
I know it, it's wrong. It's bbcode, no xbbcode markup...
