### ISSUE TITLE
HR without slash

### ISSUE THREAD

**Issue by NicholasJohn16** [milesj/decoda#107]
Is there a way to modify self closing tags so they don't require the closing slash? Just `[hr]` instead of `[hr/]`. Thanks.

**Comment by milesj** [comment]
Sorry, there isn't. The parser requires an opening and closing tag to render correctly. The self-closing tags are a bit of a hack to make the closing tag optional. Without the forward slash, there would be no easy way to determine whether it's an open tag or self-closing tag, without re-iterating over the node tree, which I don't want to do.
