### ISSUE TITLE
Function strip() return the content two times when used after parse().

### ISSUE THREAD

**Issue by Duvo** [milesj/decoda#108]
When `$decoda->strip()` is used after `$decoda->parse()`, it returns the content two times.

### An example that works
```
$decoda = new \Decoda\Decoda('[b]Something[/b]');
$decoda->defaults();
echo $decoda->strip();
```
The above example will output:
```
Something
```

### An example that does not work
```
$decoda = new \Decoda\Decoda('[b]Something[/b]');
$decoda->defaults();
echo $decoda->parse() . "\n";
echo $decoda->strip();
```
The above example will output:
```
<b>Something</b>
SomethingSomething
```

**Comment by milesj** [comment]
This is correct. Both `parse()` and `strip()` are different methods doing different things, so echoing both of them will produce 2 outputs.

**Comment by Duvo** [comment]
But in the second example, `echo parse()` output `<b>Something</b>` and `echo strip()` output `SomethingSomething`.

`strip()` should echo only one `Something`.

**Comment by milesj** [comment]
Oh sorry, didn't notice double `Something`. After briefly looking at the code, I don't see how that would occur, but would have to dig a bit deeper.

**Comment by milesj** [comment]
This has been fixed.
