### ISSUE TITLE
parse performance on big Posts

### ISSUE THREAD

**Issue by frathe** [milesj/decoda#109]
We have a few threads with quite big posts, problem is that the parsing of these texts exceeds the maximum PHP runtime.
I striped down Decoda to the bare minimum and then tested it on my local machine with one of the problematic Threads.

``` php
public function bbDecodeForum($text)
{
  $textlen = strlen($text);
  if ($this->stopwatch) {
    $this->stopwatch
      ->start('bbDecodeForum: decode Post ' . $esPostData['id'] . ' with ' . $textlen . 'chars.');
  }
 $config = array(
   'xhtmlOutput' => false,
   'strictMode' => false,
   'escapeHtml' => true
 );
 $codedText = new Decoda($text, $config);
 $engine = new \Decoda\Engine\PhpEngine();
 $codedText
   ->setEngine($engine)
   ->setLocale('de-de')
   ->addFilter(new BBCode\BasicFilter())
   ->setMaxNewlines(3)
   ->setLineBreaks(true);
 $return = $codedText->parse();
 if ($this->stopwatch) {
   $this->stopwatch
     ->stop('bbDecodeForum: decode Post ' . $esPostData['id'] . ' with ' . $textlen . 'chars.');
 }
 return $return;
}
```

But still it need a big chunk of CPU time:
![Parsing time for big Posts](http://bilder.hifi-forum.de/max/598279/bildschirmfoto-2016-03-11-um-18-28-54_656987.png)

Is there anything I can do to increase performance?
Thanks in advance :)

-Florian

**Comment by milesj** [comment]
Could you paste me one of those large character posts? How complex is the bbcode within each one?

**Comment by frathe** [comment]
Sure thing. Here is one: http://pastebin.com/nyhE4Gbc

**Comment by frathe** [comment]
Any updates on this? Are any more Inforamtion needed?

**Comment by milesj** [comment]
Sorry, no update. I've been out of town for about a week and haven't been able to look at it besides the initial post. But from the looks of it, I'm not sure there's a way to fine tune it without a rewrite (which probably won't happen).

When I used this class on my forums, I usually went with either of these approaches:

1) I had a column in the database called `content`, which is the Decoda code, and another column called `content_html`, which is the Decoda parsed to HTML. This approach works wonderfully, in that Decoda parsing is only triggered when a post is created or updated, and not continuously on the page. However, it does increase the amount of storage used in the database.

2) If you're worried about storage space, the second option would be to save the parsed Decoda into memcache/redis, and retrieve it alongside the record whenever the database is queried.

Hope this helps.

**Comment by milesj** [comment]
Can you paste an example post again? The last one expired.

**Comment by milesj** [comment]
I started working on a caching layer, which will make Decoda much faster on subsequent parses.

https://github.com/milesj/decoda/commit/f9046546375b0d4f036595391fe9b1a78fa82132

**Comment by frathe** [comment]
Sorry for the late answer ;)
Sure thing ... here you go ...
http://pastebin.com/7tmg3DkU

**Comment by milesj** [comment]
Added a caching layer in 6.8.0.
