### ISSUE TITLE
White space in attributes

### ISSUE THREAD

**Issue by Azenet** [milesj/decoda#111]
Hi,

When doing something like `[font=Times New Roman]` with strict mode disabled, the output is `...font-family: Times`. I realize this might have been done on purpose to support other things, but since I need this feature I did this : 900a643f6e5004325efdd5b7bdeb96d904af9024

This does not break tests, however there's probably a better solution for this (or just no support), hence the lack of pull request.

**Comment by milesj** [comment]
Yeah, I'm not sure this is something I want to support. The non-strict mode was only really meant to support old forums bbcode implementations.
