### ISSUE TITLE
Colors, links and text sizes are not showing

### ISSUE THREAD

**Issue by glowdemon1** [milesj/decoda#112]
Hello, everything displays properly on my forums and works, until I use Decoda to parse the bbcode. Take a look at this file http://www.hastebin.com/raw/buzapaxeve  - I may have missed something, or this may be a bug. I'm unsure and hope you can guide me, thank you.

**Comment by milesj** [comment]
You probably need to disable strict mode: `$bbcode->setStrict(false)`.
