### ISSUE TITLE
Emoticons not parsed when having the &nbsp; next to it

### ISSUE THREAD

**Issue by sauls** [milesj/decoda#114]
For example these are not parsed.

&nbsp;:);nbsp;
:);nbsp;:D
;nbsp;:)

;nbsp;:);nbsp;:);nbsp;:);nbsp;:) and so on ...

The string I get before the escapeHtml is: ":) :) :) :) :)" and after the escapeHtml is executed the string becomes as ":)nbsp;:)nbsp;:)nbsp;:)nbsp;:)" so the emoticons are not parsed at all...

**Comment by milesj** [comment]
`escapeHtml()` does not convert spaces to `&nbsp;`. Are you sure they don't already exist in the string before being sent to Decoda?

Emoticons require whitespace around the ASCII to work correctly. At most, I could remove `&nbsp;`, but that should probably be done on your end.

**Comment by sauls** [comment]
Well I think it does exists before the escaping, it all comes from wysiwyg editor, when posting from html window i guess it posts with the &nbsp; and then I post in raw data everythinh is working well.

Well maybe you are right, I should clean the string before parsing it.

**Comment by QuozPowa** [comment]
Sorry for this new response but if I understand correctly, if the emoticons are separated by special spaces  (such as these : https://fr.wikipedia.org/wiki/Aide:Liste_de_caract%C3%A8res_sp%C3%A9ciaux#Espaces_fine_et_ins.C3.A9cable), then the emoticons are not parsed ?
