### ISSUE TITLE
Uppercase Tags don't set defaults

### ISSUE THREAD

**Issue by Novynn** [milesj/decoda#115]
`[URL="http://google.com"]Google![/url]`

The href isn't parsed as comparing the tag with the key is a case sensitive proceedure [as seen here](https://github.com/milesj/decoda/blob/master/src/Decoda/Decoda.php#L1146).

The solution on my end was just to force all attribute keys to be lowercase, but thought I'd point it out here.

**Comment by milesj** [comment]
Fixed in 6.8.0.
