### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by vladrusu** [milesj/decoda#116]
Decoda EmailFilter/ClickableHook fails if after the email address you add a dot.

For example:

example@x.com. This email link will be ignored. BUG 1!

Also, the following smileys are not parsed: :( :( :(((((((((((
BUG 2!

**Comment by milesj** [comment]
The email problem looks like a legitimate bug, while, the emoticon one is correct, as emoticons require word boundaries (they must be spaced apart).

However, I don't really have time to fix this, but open to PRs.

**Comment by vladrusu** [comment]
Hello !
Thank you for the answer.
The ecomtioncs are already separated by a space... That's why I believe it's a bug as well.
I'll try to open a PR in the next days, thanks.

**Comment by vladrusu** [comment]
Update: Added #124 which fixes these bugs.
