### ISSUE TITLE
Links and ClickableHook

### ISSUE THREAD

**Issue by dimak08** [milesj/decoda#129]
Hello,

I have problem with links and ClickableHook.

Prev:
http://google.com/example/links => 
`<a href="http://google.com/example/links">http://google.com/example/links</a>`

Now:
http://google.com/example/links => 
`<a href="http://google.com">http://google.com</a>/example/links`

**Comment by milesj** [comment]
@vladrusu This may be related to your last change.

**Comment by vladrusu** [comment]
Hello !
I confirm the issue.
I created a pull request (#130), hopefully @milesj can take a look at it.

Regards. ;-)

**Comment by nanawel** [comment]
Hi @milesj. Is this gonna be fixed in a new release soon?
Thanks

**Comment by milesj** [comment]
@nanawel I believe there's still a change in the PR waiting for @vladrusu

**Comment by nanawel** [comment]
Oh right, didn't see that sorry. Anyway, seems like this PR is dead, and this bug is a bit annoying :\

**Comment by milesj** [comment]
If he doesn't response anytime soon, I'll merge the PR and make the changes myself.

**Comment by nanawel** [comment]
Hi @milesj. No response from @vladrusu. Do you think you can take care of the pending PR?

**Comment by milesj** [comment]
Merged @vladrusu PR.
