### ISSUE TITLE
Support for BBCode standalone tags?

### ISSUE THREAD

**Issue by cheryllium** [milesj/decoda#132]
For example, say I want to make a custom tag that is just: 

    [foobar]

There is no closing tag `[/foobar]`, it's meant to be a standalone tag that turns into some output. Maybe it has some customizable attributes, such as: 

    [foobar=blue]
    [foobar=red]
    [foobar color=red]

And these might be used in the template that creates the output. 

Right now, in my custom filters, if I do not have a closing `[/foobar]` tag, my code isn't parsed at all. Adding the closing tag causes it to be parsed correctly. Is there a way to remove the closing-tag requirement for specific tags? 

Thanks, and apologies if it's mentioned in the documentation somewhere, I couldn't find this in the manual. If there's a better place to ask questions like this, please let me know for the future :)

**Comment by cheryllium** [comment]
I just noticed #67 seems to address this issue. It sounds like you are set on the trailing slash being a hard requirement for these tags. 

However, I'd like to ask why this is always the case. If the parser knows a certain tag is always standalone, then shouldn't it be able to parse that correctly even without the trailing slash? There is no ambiguity to address, because the parser would know in that case not to look for a closing tag. Would it be possible to add a flag to let the parser know if a custom tag will always be standalone, so that the trailing slashes aren't necessary? 

I think it would be good if this feature could be added, because it's common to have standalone tags in bbcode-based filters and it's a pain to have to pre-process the input to add slashes every time. I'd like to only pass the input into Decoda, not another parser beforehand - it seems less redundant if it can be built into Decoda somehow.

**Comment by milesj** [comment]
It's because filters aren't loaded until after the first parsing phase, so we don't actually know if a tag is stand alone or not, as that setting is now on the filter, instead of being a parser construct: https://github.com/milesj/decoda/blob/master/src/Decoda/Decoda.php#L1415

**Comment by cheryllium** [comment]
Thanks for the response. If you have no objections, I can investigate if it is possible and submit a pull request if I find a solution. I just wanted to check with you first.

**Comment by milesj** [comment]
Yeah that's fine. I'd opt for a setting on the `Decoda` instance, like, `allowStandAlone` or something, for backwards compat.
