### ISSUE TITLE
Library Broken with PHP 7.3

### ISSUE THREAD

**Issue by rjhllr** [milesj/decoda#144]
This library is broken when used with PHP 7.3 ([via this RFC](https://wiki.php.net/rfc/continue_on_switch_deprecation)):
![image](https://user-images.githubusercontent.com/6401945/51381980-df87e880-1b15-11e9-892f-e0d9d1c17906.png)

**Comment by milesj** [comment]
We're aware, new tag will be published soon: https://github.com/milesj/decoda/pull/143

**Comment by rjhllr** [comment]
missed that, thanks!
