### ISSUE TITLE
PHP5.6+?

### ISSUE THREAD

**Issue by dereuromark** [milesj/decoda#146]
Hi!
Any plans on going to a more modern PHP version here as minimum? 5.6 would be a good fit.
That might also make it possible to use a few newer functionality, and [] arrays etc.
At this point all previous PHP versions are long EOL.
You can then simplify travis matrix, and instead add 7.4

I would also recommend adding phpstan or alike, as this prevents quite a few accidental mistakes in code.
Level 5 is usually a good level.

**Comment by milesj** [comment]
@dereuromark I haven't written PHP in about 5 years, so probably not likely. Feel free to fork it, or if you're interested, I could give you contributor access.

**Comment by dereuromark** [comment]
Sure, I can do some maintenance work
prepare also for PHP 8 etc.

From all the BBCode solutions I checked yours seems to be the cleanest in terms of extendability (not one class doing all).

**Comment by milesj** [comment]
@dereuromark Works for me. I sent you a collaborator invite.
