### ISSUE TITLE
PHP7.2+

### ISSUE THREAD

**Issue by dereuromark** [milesj/decoda#148]
I will open this as a follow up for https://github.com/milesj/decoda/issues/146

Once we released a new PHP5.6+ (with PHP7.4 compatibility) we will need to cut the PHP5 part
It is not possible to have both PHP8 support and also still 5 (typehints are required here for PHPUnit to work for example).

Are you OK tagging a new minor for PHP7.2+? 
We wouldn't have to change the code itself, and introduce no BC breaks.
Just a narrowed version window.
it is just so that it can be used again for both major versions long term.

**Comment by milesj** [comment]
@dereuromark Dropping a major version (5.x) kind of seems like a breaking change to me. Guess I'm not understanding this line:

> it is just so that it can be used again for both major versions long term.

**Comment by dereuromark** [comment]
Usually you would also add typehints etc
We could do that and make a clean major. Also fine for me.

**Comment by milesj** [comment]
Is that what you're thinking?

- 6.13 - PHP 5.6+
- 6.14 - Drop 5.6, 7.4+
- 7.0 - 8.0+ with type hints

**Comment by dereuromark** [comment]
We can also leave out the 6.14
Probably no value.

**Comment by milesj** [comment]
Yeah, sounds good to me.

**Comment by dereuromark** [comment]
https://github.com/milesj/decoda/pull/150 is open to further collect all major changes there.

We can keep master as is for now until we are ready to do the jump.
