### ISSUE TITLE
[Feature] Add attributes to [url] and [td]

### ISSUE THREAD

**Issue by vansante** [milesj/decoda#91]
Hello,

I have two feature requests: Could you add support for `target="_blank"` on the `[url]` tag and `width="xx"` on the `[td]` tag?

Thanks!

**Comment by vamsiikrishna** [comment]
Should it be htmlAttributes ?

**Comment by milesj** [comment]
The `attributes` is for Decoda attributes and `htmlAttributes` is for HTML attributes to directly put on the parsed tag.
