### ISSUE TITLE
Parse emoticons last

### ISSUE THREAD

**Issue by serpro** [milesj/decoda#96]
I have this issue when I type a text like `check this:[size:"14"]blah blah[/size]`
`:[` is converted into an emoticon so it breaks the rest of the bbcode

**Comment by milesj** [comment]
How are you adding the hooks? You can simply add the emoticon hook last.

**Comment by serpro** [comment]
I just changed on line 79 (EmoticonHook.php)

```
    public function beforeParse($content) {
```
with
```
    public function afterParse($content) {
```

and it worked fine.

**Comment by alquerci** [comment]
@serpro we need to know your Decoda configuration to dump a test case.

**Comment by serpro** [comment]
This is a simplified version of my viewHelper

```
$emoticonsConfig = array(
    'bbcode' => array(
        'emoticons' => array(
            'path' => '/images/emoticons/',
            'extension' => array( 'gif', 'png' ),
        ),
    )
);
$bbcode = new Decoda($text);
$bbcode->defaults();
$bbcode->removeHook('Censor');
$bbcode->addHook(new EmoticonHook($emoticonsConfig));
$bbcode->setLineBreaks(true);
return $bbcode->parse();
```

**Comment by alquerci** [comment]
@serpro you have an old Decoda version try to upgrade it.

**Comment by milesj** [comment]
Yeah, updating to the latest *should* fix the problem. If not, we can look at it.
