### ISSUE TITLE
Cannot parse emoticons at start.

### ISSUE THREAD

**Issue by javier-lavida** [milesj/decoda#98]
I'm trying to parse a text like this:
"
:) Hello
text text text :) :D :(
"

The last three emoticons are being parsed correctly but the first one isn't.  I don't know if it's my configuration

I figured out that emoticons require whitespaces surrounding. Is there any workaround?
I want to use this plugin with sceditor. I also want to smileys like :):):) being parsed. I could avoid using smileys like that and limit my users to just use smileys with colons.

**Comment by alquerci** [comment]
Hi @javier-lavida 

What Decoda version are you running?

**Comment by javier-lavida** [comment]
Hi @alquerci I'm running version 6.6.2. Here's a screenshot of the output.

![captura de pantalla 2015-04-09 a las 18 20 30](https://cloud.githubusercontent.com/assets/4512108/7079054/45369422-dee5-11e4-9114-f97145867699.png)

**Comment by milesj** [comment]
That's odd since they are covered by the unit tests: https://github.com/milesj/decoda/blob/master/tests/Decoda/Hook/EmoticonHookTest.php#L55

**Comment by javier-lavida** [comment]
I created another post and this happened: 
![captura de pantalla 2015-04-09 a las 18 40 44](https://cloud.githubusercontent.com/assets/4512108/7079288/07718b08-dee8-11e4-93ca-b9acee311fb7.png)

I don't understand what's happening :( both start the same

**Comment by javier-lavida** [comment]
I solved it. It's not the plugin. It's the wysiwyg editor in the browser. It sends the `&nbsp;` .
Guess I have to fix it in the browser side. However, my only question left is, is the any way to allow emoticons without surrounding whitespaces??

**Comment by milesj** [comment]
I don't believe it's possible. We need a word boundary or else we have problems with words like "http://google.com" where :/ would be matched.

**Comment by alquerci** [comment]
Using the PCRE word boundary `\b` like on the `CensorHook` does not help. The problem is that all characters can be used to form an emoticon.
